// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czrjyjwmruigjhdcwsal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6cmp5andtcnVpZ2poZGN3c2FsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NTU3NTYsImV4cCI6MjA2MTQzMTc1Nn0.S_kngYIy0UHsmW_RXgdKE9fCG26slNWj4vLlTw6TazQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);